login sign up
abhinav941/e-commernce pull request #7
Opened 2020-07-27 17:58 UTC by Abhishek-Shr

2020-07-27 18:09 UTC, abhinav941 requested changes

2020-07-27 18:09 UTC, abhinav941 commented on client/src/components/Filter/Filter.js
> +import React from 'react';
delete this

2020-07-27 18:09 UTC, abhinav941 commented on client/src/components/Login/index.js
> +import styled from "styled-components";
fix import order

2020-07-27 18:09 UTC, abhinav941 commented on client/src/components/Login/index.js
> +import styled from "styled-components";
default import
one line space
named import 
one line space 
code.....

2020-07-27 18:09 UTC, abhinav941 commented on client/src/components/ProductStack/ProductItem/index.js
>  // import './ProductItem.css';
remove if not used

2020-07-27 18:09 UTC, abhinav941 commented on client/src/components/ProductStack/ProductItem/index.js
>  // import './ProductItem.css';
import order to be fixed

2020-07-27 18:09 UTC, abhinav941 commented on client/src/components/Registration/index.js
> +// import {  } from "@ant-design/icons";
remove this

2020-07-27 18:27 UTC, Abhishek-Shr commented
Aye sir !!!!

On Mon, 27 Jul, 2020, 11:40 PM Abhinav, <notifications@github.com> wrote:

> *@abhinav941* requested changes on this pull request.
> ------------------------------
>
> In client/src/components/Filter/Filter.js
> <https://github.com/abhinav941/e-commernce/pull/7#discussion_r461070170>:
>
> > @@ -0,0 +1,11 @@
> +import React from 'react';
>
> delete this
> ------------------------------
>
> In client/src/components/Login/index.js
> <https://github.com/abhinav941/e-commernce/pull/7#discussion_r461070365>:
>
> > @@ -0,0 +1,118 @@
> +import React from 'react';
> +import { Button } from 'antd';
> +import styled from "styled-components";
>
> fix import order
> ------------------------------
>
> In client/src/components/Login/index.js
> <https://github.com/abhinav941/e-commernce/pull/7#discussion_r461073745>:
>
> > @@ -0,0 +1,118 @@
> +import React from 'react';
> +import { Button } from 'antd';
> +import styled from "styled-components";
>
> default import
> one line space
> named import
> one line space
> code.....
> ------------------------------
>
> In client/src/components/ProductStack/ProductItem/index.js
> <https://github.com/abhinav941/e-commernce/pull/7#discussion_r461074059>:
>
> > @@ -1,24 +1,31 @@
>  import React from 'react';
>  // import './ProductItem.css';
>
> remove if not used
> ------------------------------
>
> In client/src/components/ProductStack/ProductItem/index.js
> <https://github.com/abhinav941/e-commernce/pull/7#discussion_r461074175>:
>
> > @@ -1,24 +1,31 @@
>  import React from 'react';
>  // import './ProductItem.css';
>
> import order to be fixed
> ------------------------------
>
> In client/src/components/Registration/index.js
> <https://github.com/abhinav941/e-commernce/pull/7#discussion_r461074649>:
>
> > @@ -0,0 +1,136 @@
> +import React from 'react';
> +import styled from 'styled-components';
> +import { Button } from 'antd';
> +import {GooglePlusCircleFilled,FacebookFilled,TwitterCircleFilled,LinkedinOutlined  } from "@ant-design/icons";
> +// import {  } from "@ant-design/icons";
>
> remove this
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/abhinav941/e-commernce/pull/7#pullrequestreview-456011940>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH3GXW425PQKJXOSRU4HPELR5W7HTANCNFSM4PJBQTOQ>
> .
>

2020-07-29 12:53 UTC, Abhishek-Shr commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
pre
	{mso-style-priority:99;
	mso-style-link:"HTML Preformatted Char";
	margin:0in;
	margin-bottom:.0001pt;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTMLPreformattedChar
	{mso-style-name:"HTML Preformatted Char";
	mso-style-priority:99;
	mso-style-link:"HTML Preformatted";
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Review changes done!! Sent from Mail for Windows 10 From: AbhinavSent: Monday, July 27, 2020 11:40 PMTo: abhinav941/e-commernceCc: Abhishek-Shr; AuthorSubject: Re: [abhinav941/e-commernce] login sign up (#7) @abhinav941 requested changes on this pull request.In client/src/components/Filter/Filter.js:> @@ -0,0 +1,11 @@+import React from 'react';delete thisIn client/src/components/Login/index.js:> @@ -0,0 +1,118 @@+import React from 'react';+import { Button } from 'antd';+import styled from "styled-components";fix import orderIn client/src/components/Login/index.js:> @@ -0,0 +1,118 @@+import React from 'react';+import { Button } from 'antd';+import styled from "styled-components";default importone line spacenamed importone line spacecode.....In client/src/components/ProductStack/ProductItem/index.js:> @@ -1,24 +1,31 @@ import React from 'react'; // import './ProductItem.css';remove if not usedIn client/src/components/ProductStack/ProductItem/index.js:> @@ -1,24 +1,31 @@ import React from 'react'; // import './ProductItem.css';import order to be fixedIn client/src/components/Registration/index.js:> @@ -0,0 +1,136 @@+import React from 'react';+import styled from 'styled-components';+import { Button } from 'antd';+import {GooglePlusCircleFilled,FacebookFilled,TwitterCircleFilled,LinkedinOutlined  } from "@ant-design/icons";+// import {  } from "@ant-design/icons";remove this—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2020-07-30 15:47 UTC, merged